### ISSUE TITLE
widget problem

### ISSUE THREAD

**Issue by ghost** [j4321/FeedAgregator#8]
hello i have installed it from the AUR  (version 1.3.0)and the widget is closing itself when i click on it or trying to resize and move, so i can't use it :/

![peek 2019-03-05 21-01](https://user-images.githubusercontent.com/45907176/53833897-f2516200-3f89-11e9-94b9-99490cb9bfe1.gif)

any idea how to find the problem? i'm using manjaro plasma and i have tried both qt and gtk ui but widget problem persist, 

thanks.

**Comment by j4321** [comment]
Hi, 
It is the this a first time install or an update? 
I cannot reproduce the issue on my computer but I am using XFCE in Archlinux. It is normal that changing the GUI toolkit did nothing because this is only affecting the system tray icons, not the widgets which are obtained with Tk. I will try to reproduce the issue using the same desktop environment as you as soon as I can.

**Comment by ghost** [comment]
first time install, thanks

**Comment by j4321** [comment]
I have at last found time to install plasma desktop on my computer and I can reproduce your issue. So I can now try to understand what is causing it and hopefully fix it.

**Comment by j4321** [comment]
I have identified the issue: plasma desktop hides windows of type 'splash' when you click on them and I have attributed the type 'splash' to my desktop widgets as a workaround to remove window decorations.

What I can do is change the window type so that the widgets will behave normally when set on always above or always below positions. However, the normal position (the window gets on top when clicked) will have window decorations (a titlebar).
